Development
CornetS28/myApple pull request #2
Opened 2019-07-17 23:25 UTC by CornetS28

Pull request!

2019-07-18 20:31 UTC, Oghenebrume50 commented
Hi, good start for this project. Few changes need to be made

2019-07-18 20:48 UTC, Oghenebrume50 requested changes
Make all these changes and submit for re-review. Kudo, for a great start

2019-07-18 20:48 UTC, Oghenebrume50 commented on index.html
> +                <ul>
Use a nav tag here instead of a ul tag,  you could even remove the header tag and just keep the nav

2019-07-18 20:48 UTC, Oghenebrume50 commented on index.html
> +                    <li><input type="search" name="search" placeholder="&#128269"></li>
close the character reference with a semi-colon

2019-07-18 20:48 UTC, Oghenebrume50 commented on index.html
> +                </h3>
The content in the main tag are actually images not text follow this bullet point
- [ ] Each link is an <a> HTML tag, with a <div> tag inside it.
- [ ] The <div> tag  inside the <a> tag should use an image as background.

2019-07-18 20:48 UTC, Oghenebrume50 commented on index.html
> +       <br>   <br>   <br>   <br>   <br><br><br><br><br><br><br>
remove these `<br>`  and actually use CSS to put in space you need

2019-07-18 20:48 UTC, Oghenebrume50 commented on index.html
> +        <aside>
Move this aside tag and it's content into the footer, follow this guidelines for the footer
## Footer
* [ ] It should be wrapped by `<footer>` tags
* [ ] The top part is made of four `<a>` tags with `<div>` tags inside it
* [ ] The `<div>`s inside the `<a>` tags should use an image as a background
* [ ] The bottom part should include links like copyright, terms of use, and privacy policy

2019-07-23 02:11 UTC, Torres-ssf commented
### Pull Request Under Review By Sérgio (TSE)

2019-07-23 02:21 UTC, Torres-ssf commented
### Nicely done  👍
Great job on this project. But before merging to master, we need to do some changes to make it in line with Microverse guidelines.

- Navbar

- [ ]  The input tag from the navbar should have the focus effect enabled.

- Main content

- [ ] Main content links (The 3 main sentences)

- [ ] There should be three links (each one inside an anchor tag).

- [ ] Each link is an a tag, with a div tag inside it.  

- [ ] The div tag inside the anchor tag should use an image as background. The text on the original page is actually an image. This approach is required by Microverse guidelines. There is no need to use img tag here. Only a tag and div.

- Footer

- [ ]   The top part is made of four a tags with div tags inside it

- [ ] The divs inside the anchor tags should use an image as a background. The same approach of the 3 main sentences.

Kindly make these changes and submit for code review again!

2019-07-23 02:29 UTC, CornetS28 commented
Hello Sergio,

I successfully found your email. Kindly tell me where I find the
requirements for the project as do not see the for some reasons.
Best regards
Samuel

On Mon, Jul 22, 2019, 10:21 PM Sérgio Torres <notifications@github.com>
wrote:

> Nicely done 👍
>
> Great job on this project. But before merging to master, we need to do
> some changes to make it in line with Microverse guidelines.
>
>    -
>
>    Navbar
>    -
>
>    The input tag from the navbar should have the focus effect enabled.
>    -
>
>    Main content
>    -
>
>    Main content links (The 3 main sentences)
>    -
>
>    There should be three links (each one inside an anchor tag).
>    -
>
>    Each link is an a tag, with a div tag inside it.
>    -
>
>    The div tag inside the anchor tag should use an image as background.
>    The text on the original page is actually an image. This approach is
>    required by Microverse guidelines. There is no need to use img tag here.
>    Only a tag and div.
>    -
>
>    Footer
>    -
>
>    The top part is made of four a tags with div tags inside it
>    -
>
>    The divs inside the anchor tags should use an image as a background.
>    The same approach of the 3 main sentences.
>
> Kindly make these changes and submit for code review again!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CornetS28/myApple/pull/2?email_source=notifications&email_token=ALS2UR23MKVXJDNDBRZOUZLQAZTKJA5CNFSM4IEVQEIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2RWZUY#issuecomment-514026707>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALS2UR224WYSV2HH4TNRXGDQAZTKJANCNFSM4IEVQEIA>
> .
>

2019-07-23 02:47 UTC, Torres-ssf commented
At the current moment, these guidelines are only available for the TSE team. They were created by the Microverse team. The suggested changes were copied from the guidelines.

2019-07-23 21:35 UTC, mosaaleb commented
## Currently reviewing

2019-07-23 22:07 UTC, mosaaleb requested changes
## Hi @CornetS28 :wave:

### Well done working on this project :clap:. I know that you have put a lot of effort into this project, yet there is some requirements mentioned by previous reviewers are not met yet. 

See my comments below.

Also I see there is a duplicate styles in both `index.css` and `styles.css` like `wrap-all` class. A way to make sure we don't have duplicates and having healthy style guidelines is to use [`stickler`](https://github.com/microverseinc/linters-config/tree/master/css). I highly recommend to use it before moving on.

Please sumbit a new code review once you handle these requirements.

Feel free to contact me on slack if you have any questions.
## Happy coding :computer:

2019-07-23 22:07 UTC, mosaaleb commented on index.html
> +              <header class="elements first-item">
There is no `wrapp-all` styles in your css files, its `wrap-all`, may be a misspel. I have tried to apply your styles to this div, but it breaks the page.

2019-07-23 22:07 UTC, mosaaleb commented on index.html
> +                      iPad in their unique ways to add to the world's story.</h2></a>
The three text are actually images
- [ ] The `<div>` tag  inside the `<a>` tag should use an image as background -- [ ] The text on the original page is actually an image

2019-07-23 22:07 UTC, mosaaleb commented on index.html
> +              <div class="links l2">
It's against best practices to use inline styling as it is harder to debug and also harder to change in the future.

2019-07-24 23:46 UTC, samgaco commented
### Hi @CornetS28 :hand: 

### Good job and congratulations :tada: the project is approved.

Just consider these **suggestions** before merging to the master branch:

* Correct errors in the index file pointed out by https://validator.w3.org/
* Add a short description of the project and what you tried to achieve in the readme file
* Removing the red-colored borders from the navigation bar

### Anyways, the project is approved and you can merge to the master branch and submit the project completion form :muscle: Regards!

2019-07-25 00:14 UTC, CornetS28 commented
Thank you very much!!!

On Wed, Jul 24, 2019, 7:46 PM samgaco <notifications@github.com> wrote:

> Hi @CornetS28 <https://github.com/CornetS28> ✋ Good job and
> congratulations 🎉 the project is approved.
>
> Just consider these *suggestions* before merging to the master branch:
>
>    - Correct errors in the index file pointed out by
>    https://validator.w3.org/
>    - Add a short description of the project and what you tried to achieve
>    in the readme file
>    - Removing the red-colored borders from the navigation bar
>
> Anyways, the project is approved and you can merge to the master branch
> and submit the project completion form 💪 Regards!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CornetS28/myApple/pull/2?email_source=notifications&email_token=ALS2UR77KCG75DP47YQ2NODQBDSWBA5CNFSM4IEVQEIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2X5LBA#issuecomment-514839940>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALS2UR7YH273X2D3G2HM7KLQBDSWBANCNFSM4IEVQEIA>
> .
>

2019-07-25 03:19 UTC, merged